package com.hprocoder.utils;

public class TechnicalMessageUtils {

  public static final String UNSUFFICIENT_DATA_READ_FILE_CONTENT = "UNSUFFICIENT DATA READ FILE CONTENT";
  public static final String UNSUFFICIENT_DATA_READ_FILE_CONTENT_LENGTH = "UNSUFFICIENT DATA READ FILE CONTENT LENGTH";
  public static final String ENABLE_SAVE_FILE_IN_DISK = "ENABLE TO SAVE FILE IN DISK";
  public static final String UNSUFFICIENT_DATA_READ_FILENAME = "UNSUFFICIENT DATA TO READ FILENAME";
  public static final String UNSUFFICIENT_DATA_READ_FILENAME_LENGTH = "UNSUFFICIENT DATA READ FILENAME LENGTH";
  public static final String ENABLE_TO_FIND_FILE_WITH_GIVEN_ID = "ENABLE TO FIND FILE WITH GIVEN ID";
}
